### ISSUE TITLE
Channel Homepage shortcut

### ISSUE THREAD

**Issue by maxTerr** [guillaume-gomez/youtube-channels-shortcuts#9]
Le raccourci "channel" actuel n'est que très peu utile. 
Je propose de le remplacer par la homepage de la chaine. 
Le lien prend la forme : "https://www.youtube.com/channel/"CHANNELID"
Par exemple : https://www.youtube.com/channel/UC-PrBbBlScO9CmH_51fXqhQ

Merci guigui, poursuivons cet outil incroyable :D

**Comment by guillaume-gomez** [comment]
Hello,
Désolé pour le retard dans ma réponse :)
La demande existe deja, c'est le bouton `channel page`

![channelpage](https://user-images.githubusercontent.com/5362875/103446021-24fa3d80-4c7b-11eb-9831-f3634924f65f.png)
